### ISSUE TITLE
Separate linear program generation from solving it

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/ccm-milp#12]
`ccm-milp.py` should be split in two:
- one part responsible for the entirety of the linear program creation (all the way to the generation of the `.lp` file)
- one part responsible for loading up the LP, and solving it (and printing out the results).

This will allow for non-PuLP based testing of the former.

**Comment by maxime-bfsquall** [comment]
@ppebay reading a .pl file seems to be complicated, it is not possible with pulp, on the other hand we can generate a .mps problem file instead which we can then read with pulp. If reading a .pl file is mandatory I can further my research.

**Comment by maxime-bfsquall** [comment]
Currently, the script is separated : 
- `ccm_milp_problem.py` to generate the `problem.pl` and `problem.mps` files
- `ccm_milp_solver.py` to solve a problem from a `.mps` file and generate `.sol` file

pulp doesn't have methods to read an existing `.pl` file
but pulp allow to load a `.mps` file and choose a solver installed on the machine to solve the problem

Is it ok or do I have to further my research ?

**Comment by ppebay** [comment]
Issue is resolved with PR #11
