### ISSUE TITLE
Create non-regression tests

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/ccm-milp#6]
These should at a very least verifiy some of the examples discussed in the illustrations provided in #1

**Comment by tlamonthezie** [comment]
Hello @ppebay I have added 2 examples: ccm example (no cluster) and ccm example (with cluster: tasks belonging to different ranks sharing the same block) as talked discussed in #1. For some data I integrated some data that was used in lbaf: task loads, shared block sizes.
Would you be so kind to confirm that this is the request ?
