### ISSUE TITLE
Add capability to compare computed distributions with other tools

### ISSUE THREAD

**Issue by ppebay** [DARMA-tasking/ccm-milp#8]
The goal of this issue to introduce, ultimately as past of Ct, the ability to compare the computed optima vs
* `temperedLB` in vt
* LBAF when comparable models are available (e.g. no $\delta$)

@lifflander integrating your script to extract the computed solutions from them LP"s computed solution, could be made part of this issue too.

**Comment by lifflander** [comment]
Here are the pointers to my scripts:
- Python script to create a permutation based on a solution file: https://github.com/DARMA-tasking/sc24-gemma-paper/blob/main/ilp-python/generate_permutation_sol.py
- Perl script to permute JSON files based on the permutation generated from the Python script: https://github.com/DARMA-tasking/sc24-gemma-paper/blob/main/ilp-python/permute-json.pl
- Perl script to generate a Python input for the MILP: https://github.com/DARMA-tasking/sc24-gemma-paper/blob/main/ilp-python/parse-json.pl
